
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

public class CustomerInfo extends javax.swing.JFrame {

   
    public CustomerInfo() {
        initComponents();
        this.setLocationRelativeTo(null);  
        Connect();
    }
    Connection con;
    
    public void Connect(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/food", "root", "");
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(CustomerInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Address = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NameText = new javax.swing.JTextField();
        AddText = new javax.swing.JTextField();
        PnumText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Address1 = new javax.swing.JLabel();
        customerINFO = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Address.setBackground(new java.awt.Color(51, 51, 51));
        Address.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        Address.setText("NAME:");
        getContentPane().add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 80, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel4.setText("Phone Number: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 200, 30));

        NameText.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        NameText.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        NameText.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        NameText.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        NameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextActionPerformed(evt);
            }
        });
        getContentPane().add(NameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 270, 30));

        AddText.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        AddText.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        AddText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTextActionPerformed(evt);
            }
        });
        getContentPane().add(AddText, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 260, 30));

        PnumText.setFont(new java.awt.Font("Times New Roman", 2, 12)); // NOI18N
        PnumText.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PnumText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PnumTextActionPerformed(evt);
            }
        });
        getContentPane().add(PnumText, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 190, 30));

        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jButton1.setText("Enter");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, -1, -1));

        Address1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        Address1.setText("Address:");
        getContentPane().add(Address1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 110, 30));

        customerINFO.setBackground(new java.awt.Color(255, 255, 255));
        customerINFO.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        customerINFO.setText("CUSTOMER INFORMATION ");
        getContentPane().add(customerINFO, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 481, 40));

        jButton2.setText("Admin");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 60, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CUSTOMER INFORMATION.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-230, -30, 1370, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String name = NameText.getText().trim(); 
    String Address = AddText.getText().trim(); 
    String Pnum = PnumText.getText().trim(); 

    
    if (name.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Name field cannot be empty. Please enter your name.", 
            "Input Error", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    
    if (!name.matches("[a-zA-Z\\s]+")) { 
        JOptionPane.showMessageDialog(this, 
            "Name must contain only letters.Please correct it.", 
            "Input Error", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

   
    if (Address.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Address field cannot be empty. Please enter your address.", 
            "Input Error", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

   
    if (!Address.matches("[a-zA-Z\\s]+")) { 
        JOptionPane.showMessageDialog(this, 
            "Address must contain only letters.Please correct it.", 
            "Input Error", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

  
    if (!Pnum.matches("\\d+")) { 
        JOptionPane.showMessageDialog(this, 
            "Phone number must contain only numeric characters.", 
            "Input Error", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        
        PreparedStatement pst = con.prepareStatement("INSERT INTO customerinfo (name, address, PhoneNumber) VALUES (?, ?, ?)");
        pst.setString(1, name);
        pst.setString(2, Address);
        pst.setString(3, Pnum);

        int k = pst.executeUpdate();
        if (k == 1) {
            JOptionPane.showMessageDialog(this, "Record Added Successfully!");
            NameText.setText("");
            AddText.setText("");
            PnumText.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Record failed to save.");
        }
    } catch (SQLException ex) {
        Logger.getLogger(CustomerInfo.class.getName()).log(Level.SEVERE, null, ex);
    }

    Menu menuFrame = new Menu();      
    menuFrame.setVisible(true);
    this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void PnumTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PnumTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PnumTextActionPerformed

    private void NameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextActionPerformed

    private void AddTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddTextActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Admin adminFrame = new Admin();
        adminFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddText;
    private javax.swing.JLabel Address;
    private javax.swing.JLabel Address1;
    private javax.swing.JTextField NameText;
    private javax.swing.JTextField PnumText;
    private javax.swing.JLabel customerINFO;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
