
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

public class Customerinformationgui extends javax.swing.JFrame {

   
    public Customerinformationgui() {
        initComponents();
        this.setLocationRelativeTo(null);  
        Connect();
    }
    Connection con;
    
    public void Connect(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/food", "root", "");
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Customerinformationgui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Address = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        NameText = new javax.swing.JTextField();
        AddText = new javax.swing.JTextField();
        PnumText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Address1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        customerINFO = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Address.setBackground(new java.awt.Color(51, 51, 51));
        Address.setFont(new java.awt.Font("SF UI Display Bd", 1, 24)); // NOI18N
        Address.setForeground(new java.awt.Color(0, 0, 0));
        Address.setText("NAME:");
        getContentPane().add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 80, 30));

        jLabel4.setFont(new java.awt.Font("SF UI Display Bd", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Phone Number: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 200, 30));

        NameText.setBackground(new java.awt.Color(231, 186, 137));
        NameText.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        NameText.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        NameText.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        NameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextActionPerformed(evt);
            }
        });
        getContentPane().add(NameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 270, 30));

        AddText.setBackground(new java.awt.Color(231, 186, 137));
        AddText.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        AddText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTextActionPerformed(evt);
            }
        });
        getContentPane().add(AddText, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 270, 30));

        PnumText.setBackground(new java.awt.Color(231, 186, 137));
        PnumText.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PnumText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PnumTextActionPerformed(evt);
            }
        });
        getContentPane().add(PnumText, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 400, 270, 30));

        jButton1.setBackground(new java.awt.Color(236, 191, 125));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("PROCEED");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 480, -1, -1));

        Address1.setFont(new java.awt.Font("SF UI Display Bd", 1, 24)); // NOI18N
        Address1.setForeground(new java.awt.Color(0, 0, 0));
        Address1.setText("Address:");
        getContentPane().add(Address1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 110, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        customerINFO.setBackground(new java.awt.Color(204, 255, 255));
        customerINFO.setFont(new java.awt.Font("SF UI Display Bd", 1, 36)); // NOI18N
        customerINFO.setForeground(new java.awt.Color(0, 0, 0));
        customerINFO.setText("CUSTOMER INFORMATION ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(customerINFO, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(customerINFO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 470, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ANOTHER BG.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String name = NameText.getText().trim(); // Get and trim the name input
    String Address = AddText.getText().trim(); // Get and trim the address input
    String Pnum = PnumText.getText().trim(); // Get and trim the phone number input

    // Validation for empty name field
    if (name.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Name field cannot be empty. Please enter your name.", 
            "Input Error", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validation for letters-only name
    if (!name.matches("[a-zA-Z\\s]+")) { // Allow only letters and spaces
        JOptionPane.showMessageDialog(this, 
            "Name must contain only letters.Please correct it.", 
            "Input Error", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validation for empty address field
    if (Address.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Address field cannot be empty. Please enter your address.", 
            "Input Error", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validation for letters-only address
    if (!Address.matches("[a-zA-Z\\s]+")) { // Allow only letters and spaces
        JOptionPane.showMessageDialog(this, 
            "Address must contain only letters.Please correct it.", 
            "Input Error", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validation for phone number (only numeric characters allowed)
    if (!Pnum.matches("\\d+")) { // Regular expression to check for digits only
        JOptionPane.showMessageDialog(this, 
            "Phone number must contain only numeric characters.", 
            "Input Error", 
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        // Prepare SQL statement to insert data
        PreparedStatement pst = con.prepareStatement("INSERT INTO customerinfo (name, address, PhoneNumber) VALUES (?, ?, ?)");
        pst.setString(1, name);
        pst.setString(2, Address);
        pst.setString(3, Pnum);

        int k = pst.executeUpdate();
        if (k == 1) {
            JOptionPane.showMessageDialog(this, "Record Added Successfully!");
            NameText.setText("");
            AddText.setText("");
            PnumText.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Record failed to save.");
        }
    } catch (SQLException ex) {
        Logger.getLogger(Customerinformationgui.class.getName()).log(Level.SEVERE, null, ex);
    }

    Menugui menu = new Menugui();
    menu.setVisible(true);
    this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void PnumTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PnumTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PnumTextActionPerformed

    private void NameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextActionPerformed

    private void AddTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customerinformationgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customerinformationgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customerinformationgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customerinformationgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customerinformationgui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddText;
    private javax.swing.JLabel Address;
    private javax.swing.JLabel Address1;
    private javax.swing.JTextField NameText;
    private javax.swing.JTextField PnumText;
    private javax.swing.JLabel customerINFO;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
