
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.ResultSetMetaData;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Paymentgui extends javax.swing.JFrame {

    public Paymentgui() {
        initComponents();
        this.setLocationRelativeTo(null);
        Connect();
        DisplayInfo();
        Total();
        Fetch();
    }  
    PreparedStatement pst;
    Connection con;
    ResultSet rs;
    int  money;
    
    public void Connect(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/food", "root", "");
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Menugui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void Total() {
        try {
            pst = (PreparedStatement) con.prepareStatement("SELECT * FROM orders");
            rs = pst.executeQuery();
            double total = 0.0;
            while (rs.next()) {
            double price = Double.parseDouble(rs.getString("Price"));
            int quantity = Integer.parseInt(rs.getString("Quantity"));
            total += price * quantity;
        }

        
        txttotal.setText(String.format("%.2f", total));
        } catch (SQLException ex) {
            Logger.getLogger(Paymentgui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void DisplayInfo() {
    try {
        pst = (PreparedStatement) con.prepareStatement("SELECT * \n" +
"FROM customerinfo \n" +
"WHERE perID = (SELECT MAX(perID) FROM customerinfo);"); // Fetch first record
        rs = pst.executeQuery();

        if (rs.next()) {
            // Display existing customer info
            name.setText(rs.getString("Name"));
            add.setText(rs.getString("Address"));
            pnum.setText(rs.getString("PhoneNumber"));
        } else {
            // Prompt user for a new record if no customer info exists
            String newName = JOptionPane.showInputDialog(this, "Enter Customer Name:");
            String newAddress = JOptionPane.showInputDialog(this, "Enter Customer Address:");
            String newPhone = JOptionPane.showInputDialog(this, "Enter Phone Number:");

            if (newName != null && newAddress != null && newPhone != null) {
                // Save new customer info
                pst = (PreparedStatement) con.prepareStatement("INSERT INTO customerinfo (Name, Address, PhoneNumber) VALUES (?, ?, ?)");
                pst.setString(1, newName);
                pst.setString(2, newAddress);
                pst.setString(3, newPhone);
                pst.executeUpdate();

                name.setText(newName);
                add.setText(newAddress);
                pnum.setText(newPhone);
            }
        }
    } catch (SQLException ex) {
        Logger.getLogger(Paymentgui.class.getName()).log(Level.SEVERE, null, ex);
    }
}
      private void Fetch(){
        try {
            int q;
            pst = (PreparedStatement) con.prepareStatement("SELECT * FROM orders\n" +
"WHERE transactID = (SELECT MAX(transactID) FROM orders);");
            rs = pst.executeQuery();
            ResultSetMetaData rss = (ResultSetMetaData) rs.getMetaData();
            q = rss.getColumnCount();
            
            DefaultTableModel df = (DefaultTableModel)PaymentTbl.getModel();
            df.setRowCount(0);
            while(rs.next()){
                Vector v2 = new Vector();
                for(int a=1; a<= q; a++){
                    v2.add(rs.getString("ProductID"));
                    v2.add(rs.getString("Name"));
                    v2.add(rs.getString("Quantity"));
                    v2.add(rs.getString("Price"));
                }
                df.addRow(v2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Paymentgui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PaymentTbl = new javax.swing.JTable();
        name = new javax.swing.JTextField();
        add = new javax.swing.JTextField();
        pnum = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Cashtxt = new javax.swing.JTextField();
        Changetxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sales = new javax.swing.JButton();
        Print = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.setForeground(new java.awt.Color(51, 102, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SF UI Display Bd", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PAYMENT");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 180, 200, -1));

        PaymentTbl.setBackground(new java.awt.Color(204, 204, 204));
        PaymentTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ProductID", "Name", "Quantity", "Price"
            }
        ));
        jScrollPane1.setViewportView(PaymentTbl);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 890, 720));

        name.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 250, 170, -1));

        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 300, 170, -1));

        pnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnumActionPerformed(evt);
            }
        });
        jPanel1.add(pnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 350, 170, -1));

        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });
        jPanel1.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 400, 170, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 250, 50, 20));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Address:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 290, -1, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Phone Number:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 340, -1, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 390, -1, 30));

        jButton1.setText("PAY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 550, 90, 30));
        jPanel1.add(Cashtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 450, 170, -1));
        jPanel1.add(Changetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 500, 170, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cash:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 450, 50, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Change:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 500, 80, -1));

        sales.setText("SALES");
        sales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesActionPerformed(evt);
            }
        });
        jPanel1.add(sales, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 550, 90, 30));

        Print.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Print.setText("PRINT");
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });
        jPanel1.add(Print, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 550, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        
        name.setEditable(false);
    }//GEN-LAST:event_nameActionPerformed

    private void pnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnumActionPerformed
        pnum.setEditable(false);
    }//GEN-LAST:event_pnumActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        add.setEditable(false);
    }//GEN-LAST:event_addActionPerformed

    private void txttotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalActionPerformed
         txttotal.setEditable(false);
    }//GEN-LAST:event_txttotalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
        // Parse the cash input by the user
        double money = Double.parseDouble(Cashtxt.getText());

        // Parse the total amount from the total text field
        double total = Double.parseDouble(txttotal.getText());

        // Calculate the change
        double change = money - total;

        // If the change is less than 0, show an error message (insufficient cash)
        if (change < 0) {
            JOptionPane.showMessageDialog(this, "Insufficient cash. Please enter a valid amount.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            // Display the change in the change text field
            Changetxt.setText(String.format("%.2f", change));
        }

    } catch (NumberFormatException e) {
        // Handle invalid input in cash or total fields
        JOptionPane.showMessageDialog(this, "Invalid input. Please enter valid numbers for Cash and Total.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void salesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesActionPerformed
    Admin ci = new Admin();
        ci.show();
        dispose();         
    }//GEN-LAST:event_salesActionPerformed

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
    generateReceipt();
    }//GEN-LAST:event_PrintActionPerformed

    private void generateReceipt() {
    StringBuilder receipt = new StringBuilder();
    receipt.append("------------ RECEIPT ------------\n");
    receipt.append("Customer Name: ").append(name.getText()).append("\n");
    receipt.append("Address: ").append(add.getText()).append("\n");
    receipt.append("Phone Number: ").append(pnum.getText()).append("\n");
    receipt.append("---------------------------------\n");
    receipt.append("Items Purchased:\n");
    receipt.append(String.format("%-20s %-10s %-10s\n", "Product Name", "Quantity", "Price"));

    // Loop through the table rows to add order details
    DefaultTableModel df = (DefaultTableModel) PaymentTbl.getModel();
    for (int i = 0; i < df.getRowCount(); i++) {
        String productName = df.getValueAt(i, 1).toString();
        String quantity = df.getValueAt(i, 2).toString();
        String price = df.getValueAt(i, 3).toString();
        receipt.append(String.format("%-20s %-10s %-10s\n", productName, quantity, price));
    }

    receipt.append("---------------------------------\n");
    receipt.append("Total: ").append(txttotal.getText()).append("\n");
    receipt.append("---------------------------------\n");

    // Show the receipt in a dialog box (or save/print it)
    JOptionPane.showMessageDialog(this, receipt.toString(), "Receipt", JOptionPane.INFORMATION_MESSAGE);
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paymentgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paymentgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paymentgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paymentgui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paymentgui().setVisible(true);
               
       
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cashtxt;
    private javax.swing.JTextField Changetxt;
    private javax.swing.JTable PaymentTbl;
    private javax.swing.JButton Print;
    private javax.swing.JTextField add;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pnum;
    private javax.swing.JButton sales;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
